### ISSUE TITLE
What will happen if all boxes are reboot?

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/docs.kubesphere.io#102]
If KubeSphere instances are not startup with OS, pls Add doc about how to restart kubesphere

**Comment by calvinyv** [comment]
@FeynmanZhou

**Comment by FeynmanZhou** [comment]
Reboot is high risk operation, is extremely not recommended to reboot since there are multiple uncertain scenarios may happen after reboot. It has been stated in the installation guide.
![image](https://user-images.githubusercontent.com/40452856/48952397-00e8b000-ef7d-11e8-95f2-6fca7e6f39c6.png)
