### ISSUE TITLE
示例一 - 部署 MySQL 有状态应用 Lab update

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#188]
第一步：创建密钥
1.2. 填写密钥的基本信息。
描述信息：简单介绍该密钥，如 MySQL 初始密码。
建议增加步骤『点击 “下一步”』

第三步：填写基本信息
描述信息：简单介绍该工作负载，方便用户进一步了解
建议增加步骤『点击 “下一步”』

第六步：服务配置
建议在开始前增加步骤『添加存储卷模板完成后点击 下一步』
建议在描述文字“参考以下截图完成参数设置”后增加步骤『点击 下一步』

**Comment by FeynmanZhou** [comment]
@shizgchina 多谢建议，已经更新到线上了，录屏也上传了，这个issue我close了。https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/quick-start/mysql-deployment/
