### ISSUE TITLE
示例二 - 部署 Wordpress 改进建议

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#191]
2.3. 下一步，设置标签为 app: wordpress-pvc，点击创建。>>> 2.3. 点击 下一步，设置标签为 app: wordpress-pvc，点击创建。

2.4. 查看存储卷列表，可以看到存储卷 wordpress-pvc 已经创建成功 >>> 2.4. 点击左侧菜单中的 存储卷 ，查看存储卷列表，可以看到存储卷 wordpress-pvc 已经创建成功

7.3. 点击左侧菜单中的 工作负载->存储卷，查看创建的部署 Wordpress，可以看到其状态显示运行中 >>> 7.3. 查看创建的部署 Wordpress，可以看到其状态显示运行中

9.3 例如，集群的公网 IP 地址为 139.198.16.160 …… 这里建议增加一个说明，让学员知道去哪里查这个集群的公网 IP 地址。如先展示 kubesphere 安装成功后的截图，里面包含了集群 IP 地址，然后在配合上 vpc 绑定的公网 IP ，以及将此公网 IP 做地址转发时的截图。

9.4. Annotation 是用户定义的 “附加” 信息，本示例暂不设置注解，点击 下一步 进入标签设置。为方便识别此应用，我们标签设置如下。点击 创建，即可创建成功。

这里建议分成两个步骤，更加清晰。例如：
9.4. Annotation 是用户定义的 “附加” 信息，本示例暂不设置注解，点击 下一步 进入标签设置。
9.5 标签设置。为方便识别此应用，我们标签设置如下，点击 创建。

10.2 LoadBalancer：如果用 LoadBalancer 的方式暴露服务，需要有云服务厂商的 LoadBalancer 插件支持，比如 QingCloud KubeSphere 托管服务 可以将公网 IP 地址的 ID 填入 Annotation 中，即可通过公网 IP 访问该服务。(如果外网访问方式设置的是 LoadBalancer，参见 应用路由 的 LoadBalancer 方式。)
上述内容其实属于备注说明，建议采用统一风格，前面加绿色竖线，标注这段话。避免它干扰目前的NodePort 选项 

10.3 注意：可能需要进行端口转发和防火墙放行对应的端口，保证外网流量能够通过需要访问的端口如 30517，否则外网无法访问。
这里建议提供 端口转发和防火墙放行截图，以避免学员设置错误，例如将 30517 转发给 80 端口。也更容易让学员知道地址转发到内网的哪个 node 节点上。

**Comment by FeynmanZhou** [comment]
@shizgchina 
9.3 例如，集群的公网 IP 地址为 139.198.16.160 …… 这里建议增加一个说明，让学员知道去哪里查这个集群的公网 IP 地址。如先展示 kubesphere 安装成功后的截图，里面包含了集群 IP 地址，然后在配合上 vpc 绑定的公网 IP ，以及将此公网 IP 做地址转发时的截图。
--------------
9.3 回复：公网 IP 不需要单独截图说明吧，用户在浏览器使用KS时，地址栏就会显示公网 IP 地址，用户对自己集群的公网 IP 应该还是明白的。

**Comment by FeynmanZhou** [comment]
@shizgchina 多谢建议，已更新：https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/quick-start/wordpress-deployment/
