### ISSUE TITLE
示例二 - 部署 Wordpress 文档修改建议

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#194]
9.3 Paths：应用规则的路径和对应的后端服务，路径填写 "/"，服务选择之前创建的服务 wordpress-service，端口填写 wordpress 服务端口 80 >>> 

9.3 Paths：应用规则的路径和对应的后端服务，路径填写 "/"，服务选择之前创建的服务 wordpress-service，端口填写 wordpress-service 服务端口 80

这里用 wordpress-service 替换原文的 wordpress 更准确，避免歧义，即作为 service 的 wordpress ，还是作为 deployment 的 wordpress .

**Comment by FeynmanZhou** [comment]
@shizgchina 
多谢建议，已更新：https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/quick-start/wordpress-deployment/
