### ISSUE TITLE
示例 4，建议添加一个截图，方便学员操作。

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#200]
3、添加完成后，可以在 应用模板 中查看新添加仓库的应用，点击应用名称为 nginx 的应用，准备部署该应用。

建议添加如下提示性截图，便于快速找到应用模板位置。
![image](https://user-images.githubusercontent.com/41432506/50509182-f3649f80-0abf-11e9-87b1-80b3d982f4df.png)

**Comment by FeynmanZhou** [comment]
已在截图中添加红色标注，感谢建议。https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/quick-start/one-click-deploy/
