### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by fuzhy** [kubesphere/docs.kubesphere.io#211]
[监控技术选型](https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/monitoring/intro/#%E7%9B%91%E6%8E%A7%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B)
第一条 “Prometheus 和 Kubenetes 天然集成...”
Kubernetes 拼写错误

**Comment by FeynmanZhou** [comment]
Hi @fuzhy ，

感谢指正， typo 已修复。

https://docs.kubesphere.io/advanced-v1.0.0/zh-CN/monitoring/intro/
