### ISSUE TITLE
[2.1] Devops 文档保留分支天数/个数歧义

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/docs.kubesphere.io#421]
Devops 文档保留分支天数/个数容易引起歧义：

输入框下的提示 默认值-1 表示将会丢弃已经被删除的分支

说明却说默认值-1 表示不自动删除分支

这个到底是删还是不删？

![Snip20191008_33](https://user-images.githubusercontent.com/18525465/66392063-6745b800-ea01-11e9-8dd0-0d1b9a55549e.png)

**Comment by soulseen** [comment]
默认值-1 表示不自动删除分支，实际环境中的文案说明是正确的。
这个应该是文档中的截图的问题，需要更新下图片

**Comment by soulseen** [comment]
默认值-1 表示的是将会丢弃已经被删除的分支，文档这里有点问题
