### ISSUE TITLE
文章需要完善的地方

### ISSUE THREAD

**Issue by yongnights** [kubesphere/docs.kubesphere.io#483]
示例七，地址:https://kubesphere.io/docs/v2.1/zh-CN/quick-start/source-to-image/
第二步：构建设置
5、配置「健康检查器」下的「容器就绪检查」，选择 「HTTP请求检查」。
路径：必填，该示例默认使用根路径 \；

根路径应该是/ ，而不是\

**Comment by yongnights** [comment]
另外，在这篇文章开头的前提条件处，新增一个前提条件：需要事先安装好DevOps

**Comment by FeynmanZhou** [comment]
Fixed： https://kubesphere.io/docs/v2.1/zh-CN/quick-start/source-to-image/
