### ISSUE TITLE
文章中需要完善的地方

### ISSUE THREAD

**Issue by yongnights** [kubesphere/docs.kubesphere.io#484]
示例十三，地址：https://kubesphere.io/docs/v2.1/zh-CN/quick-start/b2i-war/
创建服务，将它的 WAR 包（b2i-war-java8） b2i-war-java8.war 上传到 KubeSphere。

但是给出的链接地址是b2i-war-java11.war的下载地址，不匹配。。。

**Comment by FeynmanZhou** [comment]
收到，稍后替换上去，可以先用 11 去跑demo

**Comment by FeynmanZhou** [comment]
Fixed https://kubesphere.io/docs/v2.1/zh-CN/quick-start/b2i-war/
