### ISSUE TITLE
验证可插拔功能组件的安装最后的命令参数错误

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#509]
3. 除了在控制台查看组件状态，还可以通过 kubectl 命令确认可插拔的组件是否安装成功，通常情况下，当该 namespace 下的所有 Pod 状态都为 Running，则说明其安装成功。

kubectl get pod -n namespace

这里的 namespace 应该替换为真实的 kubesphere namespace :  kubesphere-system，否则该指令没有意义。

**Comment by zryfish** [comment]
是的，我们修改下

/kind documentation
/assign @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Fixed: https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/verify-components/
