### ISSUE TITLE
修改弹性伸缩时系统报错

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/docs.kubesphere.io#528]
示例 6：设置弹性伸缩
https://kubesphere.com.cn/docs/v2.1/zh-CN/quick-start/hpa/

all-in-one 环境，在执行 修改弹性伸缩 步骤时，例如将最大 pod 数值从 10 改为 6，系统报错：
HorizontalPodAutoscaler.autoscaling "hpa-1uoyeb" is invalid: spec.metrics[0].resource.target.averageValue: Invalid value: resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}: must be positive

**Comment by FeynmanZhou** [comment]
@zryfish @wansir 有空帮忙看看这个问题，石老师应该是在 [这一步](https://kubesphere.com.cn/docs/v2.1/zh-CN/quick-start/hpa/#%E4%BF%AE%E6%94%B9%E5%BC%B9%E6%80%A7%E4%BC%B8%E7%BC%A9) 复现的。

**Comment by zryfish** [comment]
修改的时候，内存的target值是不是填充成0了

**Comment by shizgchina** [comment]
是的，咱们文档就是只改 cpu，没管内存的。

**Comment by shizgchina** [comment]
刚试了下，如果内存也设置一个非 0 的值，就不报错了。我跟鹏飞反馈下，文档需要同步修改。

**Comment by shizgchina** [comment]
我知道了，那个内存不填也可以，是咱们程序自动给填 0 的。

**Comment by shizgchina** [comment]
### 修改弹性伸缩

创建后若需要修改弹性伸缩的参数，可以在部署详情页，点击 **更多操作 → 弹性伸缩**，如下页面支持修改其参数：

@鹏飞

*** 下面这个图不对，需要修改，内存那个地方不能是 0 ，咱们程序自动给填了 0，确定后会报错。应该把 0 去掉，不填，就正常了。

**Comment by FeynmanZhou** [comment]
@leoendless 这里的内存目标使用量的默认值 0 可以去掉么？或者为空也行，默认值 0 会造成石老师上面的问题。

![image](https://user-images.githubusercontent.com/40452856/71953447-356d0900-321d-11ea-8d0e-7c4b3a98cb9d.png)

**Comment by leoendless** [comment]
这个问题应该修复了，2.1.1 发布包里会包含
