### ISSUE TITLE
Screenshots need update

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/docs.kubesphere.io#644]
* [x] Any screenshots related to role should be updated since the word "Authority Settings" is changed to "Authorization Settings".  This one is low priority

* [x] https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/intro/  and the English one need to update the first screenshot since the supported  k8s versions changed to 1.17.x
<img width="349" alt="Screen Shot 2020-03-04 at 4 03 31 PM" src="https://user-images.githubusercontent.com/28859385/75857751-ac93d780-5e31-11ea-89c5-279c6a1f0bee.png">

**Comment by FeynmanZhou** [comment]
## For "Authorization Settings":
Getting Started with Multi-tenant Management:
![image](https://user-images.githubusercontent.com/40452856/75986321-d11eab00-5f28-11ea-8242-33baeae75e15.png)
App Store
![image](https://user-images.githubusercontent.com/40452856/75986386-ef84a680-5f28-11ea-999a-91a20f0548c2.png)

## For Installation screenshot
https://kubesphere.com.cn/docs/v2.1/en/installation/intro/
https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/intro/

**Comment by rayzhou2017** [comment]
verified
