### ISSUE TITLE
Incorrectly link to Chinese page 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/docs.kubesphere.io#647]
* [x] https://kubesphere.com.cn/docs/v2.1/en/installation/intro/ "air gapped installation please refer to Disconnected Installation on Multi-Node" links to a Chinese forum page.

**Comment by FeynmanZhou** [comment]
> * [x]  https://kubesphere.com.cn/docs/v2.1/en/installation/intro/ "air gapped installation please refer to Disconnected Installation on Multi-Node" links to a Chinese forum page.

Fixed, the English guide and its link have been updated to [this page](https://kubesphere.com.cn/docs/v2.1/en/installation/intro/).

https://kubesphere.com.cn/docs/v2.1/en/installation/install-ks-on-linux-airgapped/
![image](https://user-images.githubusercontent.com/40452856/76085007-2243a300-5fec-11ea-80a1-72fcc5d11b0a.png)

**Comment by rayzhou2017** [comment]
verified
