### ISSUE TITLE
guide and script are not clear logically

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/docs.kubesphere.io#661]
* [x] https://kubesphere.com.cn/docs/v2.1/en/installation/install-on-k8s-airgapped/ says a script can do all things for you. The script looks like downloading images one by one and pushing them to a registry. The doc also says two ways to download images. After download, then says pushing the images to registry using the SAME script. It is kind of confusing.

<img width="931" alt="Screen Shot 2020-03-06 at 5 30 53 PM" src="https://user-images.githubusercontent.com/28859385/76070886-44c7c300-5fd0-11ea-9bab-7823a0679b14.png">

**Comment by FeynmanZhou** [comment]
@rayzhou2017 
It seems this sentence makes you confusing:
![image](https://user-images.githubusercontent.com/40452856/76134782-f52ed900-605b-11ea-8b43-75194c851d07.png)
I think it would be well understood to change as follows:
You use a script to pull them in batch. Here is a [shell script](https://github.com/kubesphere/ks-installer/blob/master/scripts/download-docker-images.sh) for reference, you can change it according to the comments

**Comment by rayzhou2017** [comment]
Not exactly. This script does all things for you including downloading and push images. But the guide only needs pushing at the last after you follow the steps because you already download the zipped package.

**Comment by FeynmanZhou** [comment]
See following link for the updates, we have create two different scripts for download and push respectively.

https://kubesphere.io/docs/v2.1/en/installation/install-on-k8s-airgapped/

**Comment by rayzhou2017** [comment]
verified
