### ISSUE TITLE
Chinese screenshot in English doc

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/docs.kubesphere.io#666]
* [x] The HA architecture at https://kubesphere.com.cn/docs/v2.1/en/installation/master-ha/

**Comment by rayzhou2017** [comment]
Another problem, why there is only one LB in the arch? The guide says two LBs.

**Comment by FeynmanZhou** [comment]
Fixed.
https://kubesphere.com.cn/docs/v2.1/en/installation/master-ha/

**Comment by rayzhou2017** [comment]
verfied
