### ISSUE TITLE
http://yum.dockerproject.org 停止服务

### ISSUE THREAD

**Issue by Dragon-super** [kubesphere/docs.kubesphere.io#735]
该网站已停止服务

安装脚本里面会获取`https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml`  404获取失败,导致安装脚本不能继续执行

**Comment by leoendless** [comment]
这个应该不是这个项目的 issue 吧, 感觉是 installer 的

**Comment by FeynmanZhou** [comment]
English only. For Chinese question, please go to [China forum](https://kubesphere.com.cn/forum/)
@Dragon-super This might be caused by the old version of the installer. You can try to download the installer v2.1.1 again and execute the installation.

**Comment by Dragon-super** [comment]
仔细一看是的  抱歉有点粗心  可有什么解决方法

发送自 Windows 10 版邮件应用

发件人: leoendless
发送时间: 2020年6月28日 16:07
收件人: kubesphere/docs.kubesphere.io
抄送: Dragon-super; Author
主题: Re: [kubesphere/docs.kubesphere.io] http://yum.dockerproject.org 停止服务 (#735)

这个应该不是这个项目的 issue 吧, 感觉是 installer 的
